FROM mcr.microsoft.com/devcontainers/rust:1-1-bookworm AS base

# Include lld linker to improve build times either by using environment variable
# RUSTFLAGS="-C link-arg=-fuse-ld=lld" or with Cargo's configuration file (i.e see .cargo/config.toml).
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
   && apt-get -y install clang lld \
   && apt-get autoremove -y && apt-get clean -y

RUN cargo install cargo-build-dependencies

FROM base AS setup

WORKDIR /code
RUN cargo init
COPY Cargo.toml /code/Cargo.toml
COPY Cargo.lock /code/Cargo.lock
RUN cargo fetch --manifest-path /code/Cargo.toml --locked
RUN cargo build-dependencies --release  # third-party tool

FROM setup AS builder

COPY . /code
RUN cargo build --release --offline

FROM debian:bookworm

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
   && apt-get -y install libssl3 libpq5 ca-certificates \
   && apt-get autoremove -y && apt-get clean -y

ENV ROCKET_ADDRESS=0.0.0.0

EXPOSE 42424

COPY --from=builder /code/target/release/mmoldb /mmoldb

# Rocket app depends on some files in the code
# TODO Only copy necessary files
COPY . /code
WORKDIR "/code"

CMD [ "/mmoldb" ]
