FROM mcr.microsoft.com/devcontainers/rust:1-1-bookworm AS base

# Include lld linker to improve build times either by using environment variable
# RUSTFLAGS="-C link-arg=-fuse-ld=lld" or with Cargo's configuration file (i.e see .cargo/config.toml).
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
   && apt-get -y install clang lld \
   && apt-get autoremove -y && apt-get clean -y

FROM base AS setup

WORKDIR /code
RUN cargo init
COPY Cargo.toml /code/Cargo.toml
RUN cargo fetch
COPY . /code

FROM setup AS builder

RUN cargo build --release --offline

FROM debian:buster-slim

ENV ROCKET_ADDRESS=0.0.0.0
ENV ROCKET_ENV=production

EXPOSE 42424

COPY --from=builder /code/target/release/mmoldb /mmoldb

CMD [ "/mmoldb" ]
