drop table data.event_fielders;
drop table data.event_baserunners;
drop table data.events;
drop table taxa.base;
drop table taxa.fair_ball_type;
drop table taxa.position;
drop table taxa.hit_type;
drop table taxa.event_type;
alter table data.ingests set schema public;
drop schema taxa;
drop schema data;
